package com.hellohealth.domain.model.coaching

/**
 * A coaching insight for the dashboard card + screen. [text] is the short, human-readable insight
 * (from the LLM, or the rule-based fallback). [source] records where it came from so the UI can show
 * a subtle "offline coach" note when the LLM was unavailable, and so QA can tell the paths apart.
 *
 * This is NOT medical advice — the coach describes the user's own logged numbers and suggests gentle,
 * general lifestyle nudges. The system prompt enforces that; [source] never changes that contract.
 */
data class CoachingInsight(
    val text: String,
    val source: Source,
) {
    enum class Source {
        /** Generated by an LLM provider (Gemini or OpenRouter). */
        LLM,
        /** The on-device rule-based fallback (LLM unavailable / disabled / offline). */
        RULE_BASED,
    }
}
